### ISSUE TITLE
It ignores bitdepth with no warning

### ISSUE THREAD

**Issue by danialbehzadi** [FallingSnow/h265ize#96]
Hi.

Setting bitdepth 10 or 12 has no effect on a system without proper libraries. It sould at least have a warning, which tell user how to acquire them.

**Comment by FallingSnow** [comment]
This should be fixed in the next major release of h265ize.

**Comment by Kazz3r24** [comment]
Sorry, I should have put that better.
3 years later, the latest release doesn't have this fixed and no indication at all on what's missing or how to fix. I thought the work around may be to use -x and pass the bit depth options directly to ffmpeg, still no joy.

I tried running the latest ffmpeg which completely broke h265ize, forcing me to downgrade - but still unable to pass the 10bit option.

**Comment by Kazz3r24** [comment]
I might have figured this one out if anyone else reads this...

Discovered via: https://github.com/FallingSnow/h265ize/commit/a0574d40098adae8a6b555a86be010c94e740048

There's a line that describes using --10bit or --12bit instead of the described --bitdepth # for setting the bitdepth. This appears to work properly. I'm now seeing -pix_fmt yuv420p10le properly being passed as an argument.

Will update if I discover anything else, but this should really be added somewhere in the readme.
